version: 0.9.0.{build}

environment:
  packageVersion: 0.9.0

pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master

init:
- ps: $env:projectPath = ".\src\Quasar.Collections.Paging"
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:versionSuffix = "rc$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion
#- ps: $Env:DOTNET_BUILD_VERSION = "0.9.$Env:APPVEYOR_BUILD_NUMBER-CI"
#- ps: $Env:DOTNET_ASSEMBLY_FILE_VERSION = "0.9.$Env:APPVEYOR_BUILD_NUMBER"

assembly_info:
  patch: true
  file: .\src\Quasar.Collections.Paging\Properties\AssemblyInfo.cs
  assembly_version: '$(buildVersion)'
  assembly_file_version: '$(buildVersion)'
  assembly_informational_version: '$(nugetVersion)'

configuration: Release

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

#build_script:  
#- ps: $env:projectPath\Build.ps1

test: off

before_build:
- nuget restore

build:
  verbosity: minimal

#after_build:
#- ps: nuget pack "$env:projectPath\Package.nuspec" -version "$env:nugetVersion"

after_build:
- ps: dotnet pack $env:projectPath -c $env:CONFIGURATION -o .\artifacts --version-suffix=$env:versionSuffix

artifacts:
- path: .\artifacts\**\*.nupkg
  name: nuget-package

deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: iRgJLbvGvLEZPi7paKqFfCzmQ65VgpXKhL+7RU0e/OnL2/pOD9K2hi0qvleV2lKf
  artifact: nuget-package
  on:
    branch: master